fluent_flow:
  audio_recording:
    duration: 5
    sample_rate: 44100

  vosk_service:
    sample_rate: 16000

  openai_service:
    api_url: 'https://api.openai.com/v1'
    model: 'gpt-3.5-turbo'

  streamlit_app:
    host: 'localhost'
    port: 8501